### ISSUE TITLE
下载代码编辑器VS Code

### ISSUE THREAD

**Issue by shiqimei** [ahucv/Management#11]
去官网下载安装 [VS Code](https://code.visualstudio.com/) 后初步熟悉这款编辑器的用法。

**Comment by qifanzhang-ai** [comment]
done

**Comment by zhangqifannb** [comment]
done

**Comment by meijiahaoheng** [comment]
down

_Sent from my Vivo X21A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shiqimei** [comment]
> down
> 
> _Sent from my Vivo X21A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

应该是 done， done 是完成的意思，下次注意下哈~
