### ISSUE TITLE
安装ubuntu系统时的问题

### ISSUE THREAD

**Issue by meijiahaoheng** [ahucv/Management#7]
进入bios界面后，在boot sequence选项中勾选了Legacy后，找不到我的U盘所对应的部分，那个boot sequence列表是空的，这是什么问题呢

_Sent from my Vivo X21A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shiqimei** [comment]
> 进入bios界面后，在boot sequence选项中勾选了Legacy后，找不到我的U盘所对应的部分，那个boot sequence列表是空的，这是什么问题呢
> 
> _Sent from my Vivo X21A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

可以贴上你的截图吗？

**Comment by meijiahaoheng** [comment]
@lolimay 我好像找不到能贴图的地方

_Sent from my Vivo X21A using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by shiqimei** [comment]
选择 Legacy 模式后，重启再进入
